/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeatherResponse } from '../../models/weather-response';

export interface ApiWeatherLocationGet$Plain$Params {
  location: string;
}

export function apiWeatherLocationGet$Plain(http: HttpClient, rootUrl: string, params: ApiWeatherLocationGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<WeatherResponse>> {
  const rb = new RequestBuilder(rootUrl, apiWeatherLocationGet$Plain.PATH, 'get');
  if (params) {
    rb.path('location', params.location, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeatherResponse>;
    })
  );
}

apiWeatherLocationGet$Plain.PATH = '/api/Weather/{location}';
