/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChallengeResponse } from '../../models/challenge-response';

export interface ApiAuthChallengeUsernameGet$Plain$Params {
  username: string;
}

export function apiAuthChallengeUsernameGet$Plain(http: HttpClient, rootUrl: string, params: ApiAuthChallengeUsernameGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ChallengeResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthChallengeUsernameGet$Plain.PATH, 'get');
  if (params) {
    rb.path('username', params.username, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChallengeResponse>;
    })
  );
}

apiAuthChallengeUsernameGet$Plain.PATH = '/api/Auth/challenge/{username}';
