/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RouteCalculationResponse {
  distance?: (number | string);
  estimatedTime?: (number | string);
  geoJson?: (string | null);
}
