/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TourLogExport } from '../models/tour-log-export';
export interface TourExport {
  description?: (string | null);
  distance?: (number | string);
  endLocation?: string;
  estimatedTime?: (number | string);
  logs?: Array<TourLogExport>;
  routeGeojson?: (string | null);
  startLocation?: string;
  title?: string;
  transportType?: string;
}
