/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TourLog } from '../models/tour-log';
import { User } from '../models/user';
export interface Tour {
  computedChildFriendlyScore?: (number | string);
  computedPopularityScore?: (number | string);
  createdAt?: string;
  description?: (string | null);
  distance?: (number | string);
  endLocation?: string;
  estimatedTime?: (number | string);
  id?: (number | string);
  mapImagePath?: (string | null);
  routeGeojson?: (string | null);
  startLocation?: string;
  title?: string;
  tourLogs?: Array<TourLog>;
  transportType?: string;
  updatedAt?: string;
  user?: User;
  userId?: (number | string);
}
