/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Tour } from '../models/tour';
export interface TourLog {
  comment?: (string | null);
  createdAt?: string;
  difficulty?: (number | string);
  id?: (number | string);
  logDateTime?: string;
  rating?: (number | string);
  temperature?: (number | string | null);
  totalDistance?: (number | string);
  totalTime?: (number | string);
  tour?: Tour;
  tourId?: (number | string);
  updatedAt?: string;
  weatherCondition?: (string | null);
}
