/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TourLogExport {
  comment?: (string | null);
  difficulty?: (number | string);
  logDateTime?: string;
  rating?: (number | string);
  totalDistance?: (number | string);
  totalTime?: (number | string);
}
