/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Tour } from '../models/tour';
export interface User {
  createdAt?: string;
  email?: string;
  id?: (number | string);
  passwordHash?: string;
  tours?: Array<Tour>;
  updatedAt?: string;
  username?: string;
}
