/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TourExport } from '../../models/tour-export';

export interface ApiImportExportExportPost$Json$Params {
      body: Array<(number | string)>
}

export function apiImportExportExportPost$Json(http: HttpClient, rootUrl: string, params: ApiImportExportExportPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TourExport>>> {
  const rb = new RequestBuilder(rootUrl, apiImportExportExportPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TourExport>>;
    })
  );
}

apiImportExportExportPost$Json.PATH = '/api/ImportExport/export';
