/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RouteCalculationResponse } from '../../models/route-calculation-response';

export interface ApiTourCalculateGet$Json$Params {
  start?: string;
  end?: string;
  transportType?: string;
}

export function apiTourCalculateGet$Json(http: HttpClient, rootUrl: string, params?: ApiTourCalculateGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<RouteCalculationResponse>> {
  const rb = new RequestBuilder(rootUrl, apiTourCalculateGet$Json.PATH, 'get');
  if (params) {
    rb.query('start', params.start, {});
    rb.query('end', params.end, {});
    rb.query('transportType', params.transportType, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RouteCalculationResponse>;
    })
  );
}

apiTourCalculateGet$Json.PATH = '/api/Tour/calculate';
