/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TourLog } from '../../models/tour-log';

export interface ApiTourLogsIdGet$Plain$Params {
  id: (number | string);
}

export function apiTourLogsIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiTourLogsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TourLog>> {
  const rb = new RequestBuilder(rootUrl, apiTourLogsIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TourLog>;
    })
  );
}

apiTourLogsIdGet$Plain.PATH = '/api/TourLogs/{id}';
