/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TourLog } from '../../models/tour-log';

export interface ApiTourLogsTourTourIdGet$Json$Params {
  tourId: (number | string);
}

export function apiTourLogsTourTourIdGet$Json(http: HttpClient, rootUrl: string, params: ApiTourLogsTourTourIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TourLog>>> {
  const rb = new RequestBuilder(rootUrl, apiTourLogsTourTourIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('tourId', params.tourId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TourLog>>;
    })
  );
}

apiTourLogsTourTourIdGet$Json.PATH = '/api/TourLogs/tour/{tourId}';
