/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTourLogRequest } from '../../models/create-tour-log-request';
import { TourLogResponse } from '../../models/tour-log-response';

export interface ApiTourLogsPost$Json$Params {
      body: CreateTourLogRequest
}

export function apiTourLogsPost$Json(http: HttpClient, rootUrl: string, params: ApiTourLogsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TourLogResponse>> {
  const rb = new RequestBuilder(rootUrl, apiTourLogsPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TourLogResponse>;
    })
  );
}

apiTourLogsPost$Json.PATH = '/api/TourLogs';
