/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTourLogDto } from '../../models/create-tour-log-dto';
import { TourLog } from '../../models/tour-log';

export interface ApiTourLogsPost$Plain$Params {
      body: CreateTourLogDto
}

export function apiTourLogsPost$Plain(http: HttpClient, rootUrl: string, params: ApiTourLogsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TourLog>> {
  const rb = new RequestBuilder(rootUrl, apiTourLogsPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TourLog>;
    })
  );
}

apiTourLogsPost$Plain.PATH = '/api/TourLogs';
