/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TourLogResponse } from '../../models/tour-log-response';

export interface ApiTourLogsMyLogsGet$Plain$Params {
}

export function apiTourLogsMyLogsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiTourLogsMyLogsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TourLogResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiTourLogsMyLogsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TourLogResponse>>;
    })
  );
}

apiTourLogsMyLogsGet$Plain.PATH = '/api/TourLogs/my-logs';
