/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatItemResponse } from '../../models/stat-item-response';

export interface ApiStatsDashboardGet$Json$Params {
}

export function apiStatsDashboardGet$Json(http: HttpClient, rootUrl: string, params?: ApiStatsDashboardGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StatItemResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiStatsDashboardGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StatItemResponse>>;
    })
  );
}

apiStatsDashboardGet$Json.PATH = '/api/Stats/dashboard';
