/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatItemResponse } from '../../models/stat-item-response';

export interface ApiStatsDashboardGet$Plain$Params {
}

export function apiStatsDashboardGet$Plain(http: HttpClient, rootUrl: string, params?: ApiStatsDashboardGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StatItemResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiStatsDashboardGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StatItemResponse>>;
    })
  );
}

apiStatsDashboardGet$Plain.PATH = '/api/Stats/dashboard';
