/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchResult } from '../../models/search-result';

export interface ApiSearchGet$Json$Params {
  term?: string;
  type?: string;
}

export function apiSearchGet$Json(http: HttpClient, rootUrl: string, params?: ApiSearchGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchResult>> {
  const rb = new RequestBuilder(rootUrl, apiSearchGet$Json.PATH, 'get');
  if (params) {
    rb.query('term', params.term, {});
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchResult>;
    })
  );
}

apiSearchGet$Json.PATH = '/api/Search';
